/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a3c9ff",
        "tertiary": "#ffb689",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed": "#00210c",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#ffdbc8",
        "outline-variant": "#404752",
        "surface-dim": "#131313",
        "on-tertiary-container": "#ffffff",
        "error-container": "#93000a",
        "surface-bright": "#393939",
        "primary-fixed": "#d3e3ff",
        "on-primary-container": "#ffffff",
        "outline": "#8a919e",
        "on-primary": "#00315c",
        "on-secondary-fixed-variant": "#005228",
        "secondary": "#4ae183",
        "on-primary-fixed": "#001c39",
        "background": "#131313",
        "secondary-container": "#06bb63",
        "on-background": "#e5e2e1",
        "on-surface-variant": "#c0c7d4",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1b1b1b",
        "primary-container": "#0078d4",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#4ae183",
        "on-tertiary-fixed-variant": "#743500",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#0060ab",
        "tertiary-container": "#bc5b00",
        "on-error": "#690005",
        "surface-container": "#20201f",
        "surface": "#131313",
        "primary": "#a3c9ff",
        "secondary-fixed": "#6bfe9c",
        "tertiary-fixed-dim": "#ffb689",
        "surface-variant": "#353535",
        "surface-tint": "#a3c9ff",
        "inverse-surface": "#e5e2e1",
        "on-secondary": "#003919",
        "on-secondary-container": "#00431f",
        "on-tertiary": "#512300",
        "on-primary-fixed-variant": "#004883",
        "surface-container-highest": "#353535",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#311300"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-gap": "12px",
        "internal-padding": "16px",
        "container-padding": "24px",
        "base-unit": "4px"
      },
    },
  },
  plugins: [],
};